# Default values for descheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: komljen/descheduler
  tag: v0.5.0-4-ga7ceb671
  pullPolicy: IfNotPresent

schedule: "*/30 * * * *"

cmdOptions:
  v: 4
  max-pods-to-evict-per-node: 10

deschedulerPolicy:
  strategies:
    RemoveDuplicates:
      enabled: false
    LowNodeUtilization:
      enabled: true
      params:
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 20
            memory: 20
            pods: 20
          targetThresholds:
            cpu: 50
            memory: 50
            pods: 50
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
    RemovePodsViolatingNodeAffinity:
      enabled: true
      params:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
