dependencies:
- name: kibana
  version: "0.4.2"
  #repository: https://kubernetes-charts.storage.googleapis.com/
  repository: "file://../kibana"
- name: elasticsearch
  version: "0.1.3"
  #repository: https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/charts
  repository: "file://../elasticsearch"
- name: fluent-bit
  version: "0.4.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
