apiVersion: v1
entries:
  descheduler:
  - apiVersion: v1
    appVersion: v0.6.0
    created: 2018-10-08T16:24:38.035617119+02:00
    description: A Helm chart for Kubernetes Descheduler
    digest: 9eddad77998b3d4632375bfb0b9a133bde4e4a47beaf57422aee4cba4db0d73d
    name: descheduler
    urls:
    - descheduler-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: v0.5.0-4-ga7ceb671
    created: 2018-10-08T16:24:38.035347814+02:00
    description: A Helm chart for Kubernetes Descheduler
    digest: 32ca0684f33dbfe61f265537e3c87d04c43e7ac9aafeb77f44397cbaa32f6bae
    name: descheduler
    urls:
    - descheduler-0.1.0.tgz
    version: 0.1.0
  efk:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-10-08T16:24:38.036684521+02:00
    description: A Helm chart for EFK stack
    digest: 39736f7fe9e1018b2f3a5455ed0e80d417b40022487061cef766d34f39b25381
    name: efk
    urls:
    - efk-0.1.0.tgz
    version: 0.1.0
  elasticsearch:
  - apiVersion: v1
    appVersion: 6.1.3
    created: 2018-10-08T16:24:38.038165735+02:00
    description: A Helm chart for Elasticsearch cluster
    digest: eb8163d9a2153c5760e80b530a4ff8653c569b24a3cffd26a1f1be8a4e080179
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 6.1.3
    created: 2018-10-08T16:24:38.037858358+02:00
    description: A Helm chart for Elasticsearch cluster
    digest: 32a25b05c73cc92b49fc53b64d25cee44d28e1062db1ef12f2cbcb0e260d0019
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.3.tgz
    version: 0.1.3
  elasticsearch-operator:
  - apiVersion: v1
    appVersion: 0.0.12
    created: 2018-10-08T16:24:38.040434241+02:00
    description: A Helm chart for Elasticsearch operator
    digest: 5b946ae9c69685e80964599cadfcf1b675b124eb393471ee0f335e63eb572024
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: 0.0.12
    created: 2018-10-08T16:24:38.040103171+02:00
    description: A Helm chart for Elasticsearch operator
    digest: f909a7a19ec3e04259a40728c7428515701aed1f8cae7407c8b6a993b6e083d8
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 0.0.10
    created: 2018-10-08T16:24:38.038948574+02:00
    description: A Helm chart for Elasticsearch operator
    digest: dea5f18a301f11dee2aef9ac1dd3b44069e4bc128c8c32f8e1322a55a385a282
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.3.tgz
    version: 0.1.3
  hpa-operator:
  - created: 2018-10-08T16:24:38.040960343+02:00
    description: A Helm chart for Kubernetes
    digest: 3710121df9bab55fbec2113aab32902b472ed4b0bff4638c870acecd469cbfc2
    home: https://banzaicloud.com
    keywords:
    - hpa
    - autoscale
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: hpa-operator
    sources:
    - https://github.com/banzaicloud/hpa-operator
    urls:
    - hpa-operator-0.0.5.tgz
    version: 0.0.5
  k8s-spot-rescheduler:
  - apiVersion: v1
    appVersion: v0.2.0
    created: 2018-10-08T16:24:38.042222495+02:00
    description: A k8s-spot-rescheduler Helm chart for Kubernetes
    digest: efa17ca0d214dd037427682b8096ab8c47ffa9160e2f0abb490121900cf4db53
    home: https://github.com/pusher/k8s-spot-rescheduler
    keywords:
    - spot
    - rescheduler
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
    name: k8s-spot-rescheduler
    sources:
    - https://github.com/pusher/k8s-spot-rescheduler
    urls:
    - k8s-spot-rescheduler-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: v0.1.1
    created: 2018-10-08T16:24:38.041855469+02:00
    description: A k8s-spot-rescheduler Helm chart for Kubernetes
    digest: 255c56c1e35296a45dee14e8d069210a3c8ef4865b44b01b2378f3b8c1423bd2
    home: https://github.com/pusher/k8s-spot-rescheduler
    keywords:
    - spot
    - rescheduler
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
    name: k8s-spot-rescheduler
    sources:
    - https://github.com/pusher/k8s-spot-rescheduler
    urls:
    - k8s-spot-rescheduler-0.2.0.tgz
    version: 0.2.0
  kibana:
  - appVersion: 6.1.3
    created: 2018-10-08T16:24:38.04263936+02:00
    description: Kibana is an open source data visualization plugin for Elasticsearch
    digest: 17482b8ec6895ab271666a834223554857490c36acc449e87b2ba4b134b3e704
    engine: gotpl
    home: https://www.elastic.co/products/kibana
    icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
    keywords:
    - elasticsearch
    - kibana
    maintainers:
    - email: casey@monax.io
      name: compleatang
    - email: alen.komljen@live.com
      name: komljen
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - kibana-0.4.2.tgz
    version: 0.4.2
  kube-spot-termination-notice-handler:
  - apiVersion: v1
    appVersion: 1.10.8-1
    created: 2018-10-08T16:24:38.044575918+02:00
    description: Watch and action AWS spot termination events
    digest: 503e78289d4f67b5e7cc2ce8ba9f36ae4c6f76c8dc6da2a311aff58e392db3b6
    home: https://github.com/kube-aws/kube-spot-termination-notice-handler
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: akomljen.com
    name: kube-spot-termination-notice-handler
    urls:
    - kube-spot-termination-notice-handler-0.4.3.tgz
    version: 0.4.3
  - apiVersion: v1
    appVersion: 1.10.8-1
    created: 2018-10-08T16:24:38.044158091+02:00
    description: Watch and action AWS spot termination events
    digest: 12b80fcc436e40e7f43b55ccf6c9ae9405b125f31c3b9bd96a82cdc7b8e8c142
    home: https://github.com/kube-aws/kube-spot-termination-notice-handler
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: akomljen.com
    name: kube-spot-termination-notice-handler
    urls:
    - kube-spot-termination-notice-handler-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v1
    appVersion: 1.10.8-1
    created: 2018-10-08T16:24:38.043270398+02:00
    description: Watch and action AWS spot termination events
    digest: 33a11839fdb1823d25af466245875046cb83bbaab1768def1e4df2dbcdd6333e
    home: https://github.com/kube-aws/kube-spot-termination-notice-handler
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: akomljen.com
    name: kube-spot-termination-notice-handler
    urls:
    - kube-spot-termination-notice-handler-0.4.1.tgz
    version: 0.4.1
  metrics-server:
  - apiVersion: v1
    appVersion: 0.3.1
    created: 2018-10-08T16:24:38.044932653+02:00
    description: Metrics Server is a cluster-wide aggregator of resource usage data.
    digest: e1e211705364a6e7ef19fda4faec4fa316a946280f32f296cb0f65bb3880852e
    home: https://github.com/kubernetes-incubator/metrics-server
    keywords:
    - metrics-server
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: metrics-server
    sources:
    - https://github.com/kubernetes-incubator/metrics-server
    urls:
    - metrics-server-0.0.5.tgz
    version: 0.0.5
generated: 2018-10-08T16:24:38.034491908+02:00
