apiVersion: v1
entries:
  descheduler:
  - apiVersion: v1
    appVersion: v0.6.0
    created: 2018-07-17T14:38:46.447735908+02:00
    description: A Helm chart for Kubernetes Descheduler
    digest: c027c1feb60d42118ae67c4c13b855d61fa99d1eae96c89d85708b52a1fb48a9
    name: descheduler
    urls:
    - descheduler-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: v0.5.0-4-ga7ceb671
    created: 2018-07-17T14:38:46.44749845+02:00
    description: A Helm chart for Kubernetes Descheduler
    digest: 32ca0684f33dbfe61f265537e3c87d04c43e7ac9aafeb77f44397cbaa32f6bae
    name: descheduler
    urls:
    - descheduler-0.1.0.tgz
    version: 0.1.0
  efk:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-07-17T14:38:46.448667361+02:00
    description: A Helm chart for EFK stack
    digest: caef9bf0810a510360aa2f7d10f6f3a0d8dba92d6a1d98d56a5ef4df3bf8d6bb
    name: efk
    urls:
    - efk-0.1.0.tgz
    version: 0.1.0
  elasticsearch:
  - apiVersion: v1
    appVersion: 6.1.3
    created: 2018-07-17T14:38:46.449586496+02:00
    description: A Helm chart for Elasticsearch cluster
    digest: eb8163d9a2153c5760e80b530a4ff8653c569b24a3cffd26a1f1be8a4e080179
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 6.1.3
    created: 2018-07-17T14:38:46.449352791+02:00
    description: A Helm chart for Elasticsearch cluster
    digest: 32a25b05c73cc92b49fc53b64d25cee44d28e1062db1ef12f2cbcb0e260d0019
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.3.tgz
    version: 0.1.3
  elasticsearch-operator:
  - apiVersion: v1
    appVersion: 0.0.12
    created: 2018-07-17T14:38:46.451114535+02:00
    description: A Helm chart for Elasticsearch operator
    digest: 5b946ae9c69685e80964599cadfcf1b675b124eb393471ee0f335e63eb572024
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: 0.0.12
    created: 2018-07-17T14:38:46.450857809+02:00
    description: A Helm chart for Elasticsearch operator
    digest: f909a7a19ec3e04259a40728c7428515701aed1f8cae7407c8b6a993b6e083d8
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 0.0.10
    created: 2018-07-17T14:38:46.450292967+02:00
    description: A Helm chart for Elasticsearch operator
    digest: dea5f18a301f11dee2aef9ac1dd3b44069e4bc128c8c32f8e1322a55a385a282
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.3.tgz
    version: 0.1.3
  k8s-spot-rescheduler:
  - apiVersion: v1
    appVersion: v0.1.1
    created: 2018-07-17T14:38:46.451406986+02:00
    description: A k8s-spot-rescheduler Helm chart for Kubernetes
    digest: 255c56c1e35296a45dee14e8d069210a3c8ef4865b44b01b2378f3b8c1423bd2
    home: https://github.com/pusher/k8s-spot-rescheduler
    keywords:
    - spot
    - rescheduler
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
    name: k8s-spot-rescheduler
    sources:
    - https://github.com/pusher/k8s-spot-rescheduler
    urls:
    - k8s-spot-rescheduler-0.2.0.tgz
    version: 0.2.0
  kibana:
  - appVersion: 6.1.3
    created: 2018-07-17T14:38:46.45177127+02:00
    description: Kibana is an open source data visualization plugin for Elasticsearch
    digest: 17482b8ec6895ab271666a834223554857490c36acc449e87b2ba4b134b3e704
    engine: gotpl
    home: https://www.elastic.co/products/kibana
    icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
    keywords:
    - elasticsearch
    - kibana
    maintainers:
    - email: casey@monax.io
      name: compleatang
    - email: alen.komljen@live.com
      name: komljen
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - kibana-0.4.2.tgz
    version: 0.4.2
generated: 2018-07-17T14:38:46.4467221+02:00
